title: Dipanjan's webpage
description: My personal Webpage
author: Dipanjan Dutta
github: https://github.com/dipanjan1311/
about: Programmer and photographer by passion, scientist and innovator by heart
disqus_shortname: ""
google_analytics: ""
avatar_url: /static/img/me.jpg

enableTags: false
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/FelixDipanjan"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/dipanjandutta92/"
    - icon: fa-github
      link: "https://github.com/dipanjan1311"


urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Publications
      url: /pubs/
    - text: Teaching
      url: /teaching/

url: "https://dipanjan1311.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
